### ISSUE TITLE
Request support for spaces in Identifiers through use of backquotes

### ISSUE THREAD

**Issue by ibigpapa** [robinedwards/neomodel#188]
``` Python
import neomodel

neomodel.__version__
'2.0.2'

from neomodel import StructuredNode, StructuredRel, StringProperty, RelationshipTo

class InBetween(StructuredRel):
    name = StringProperty(default='in-between')

class From(StructuredNode):
    name = StringProperty(default='from')
    to = RelationshipTo('To', 'Goes To', model=InBetween)

class To(StructuredNode):
    name = StringProperty(default='to')


f = From()
f.save()
<__main__.From object at 0xd3da10>
t = To()
t.save()
<__main__.To object at 0xd3dc90>
f.to.connect(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/neomodel/relationship_manager.py", line 16, in checker
    return fn(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/neomodel/relationship_manager.py", line 92, in connect
    rel_ = self.source.cypher(q + " RETURN r", params)[0][0][0]
  File "/usr/lib/python2.7/site-packages/neomodel/core.py", line 129, in cypher
    return db.cypher_query(query, params)
  File "/usr/lib/python2.7/site-packages/neomodel/util.py", line 219, in cypher_query
    raise e
py2neo.cypher.error.statement.InvalidSyntax: Invalid input 'T': expected whitespace, comment, '|', a length specification, a property map or ']' (line 1, column 82 (offset: 81))
"MATCH them, us WHERE id(them)={them} and id(us)={self} CREATE UNIQUE(us)-[r:Goes To]->(them) SET r.name = {place_holder_name} RETURN r"
                                                                                  ^
```

**Comment by bleib1dj** [comment]
@ibigpapa We don't document it anywhere but cypher has some limitations on [identifiers](http://neo4j.com/docs/stable/cypher-identifiers.html), including relationship names. We could modify it to include ``` ` ```'s around each of the identifiers to enable spaces. To get an immediate fix though you could replace the space in 

    to = RelationshipTo('To', 'Goes To', model=InBetween)

with an underscore 

    to = RelationshipTo('To', 'Goes_To', model=InBetween)

**Comment by ibigpapa** [comment]
Thanks!

**Comment by bleib1dj** [comment]
np :)
