### ISSUE TITLE
Neomodel 2.0.2 not compatible with Py2Neo 2.0.8?

### ISSUE THREAD

**Issue by mjmare** [robinedwards/neomodel#197]
With a very simple test program I get the error below.
I'm using Neo4j-community 3.0.0-M02. I don't think that is the problem, because PyNeo works just fine with that. 

---

class Person(StructuredNode):
    name = StringProperty()
    age = IntegerProperty(default=0)

p=Person(name='Jimmy', age=3)
p.save()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/signals.py", line 25, in hooked
    val = fn(self, _args, *_kwargs)
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/core.py", line 159, in save
    self._id = self.create(self.__properties__)[0]._id
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/core.py", line 289, in create
    results = db.cypher_query(query, params)
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/util.py", line 219, in cypher_query
    raise e
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/util.py", line 211, in cypher_query
    results = self._execute_query(query, params)
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/neomodel/util.py", line 205, in _execute_query
    results = self.session.cypher.execute(query, params)
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 136, in execute
    results = tx.commit()
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/Users/mjm/Dropbox/Devel/ACHN/Sociale_kaart/venv3/lib/python3.5/site-packages/py2neo/cypher/core.py", line 288, in post
    raise self.error_class.hydrate(error)
py2neo.cypher.error.statement.InvalidType: Parameter provided for node creation is not a Map

**Comment by mjmare** [comment]
Did some additional testing:
Neomodel 2.0.2 & Py2Neo 2.0.4 or 2.0.6 & Neo4j-community 3.0.0-M02: same problem.
Neomodel 2.0.2 & Py2Neo 2.0.8 (=latest) & Neo4j-community 2.3.1: works normally. 

So it somehow is related to the Neo4j milestone release.

**Comment by Ashwanthkumard** [comment]
Facing the same issue,
Made necessary changes to the cypher syntax in neomodel 2.0.2.
Neomodel 2.0.2 & Py2Nep 2.0.7 & Neo4j-Community 3.0 : Some problem.

Able to create the nodes Using the REST API and Neo4j console. But, the problem raises when using with the Neomodel Driver.

**Comment by mjmare** [comment]
The current version of Py2Neo is 3 and it should support Neo4j 2 and 3. However Neomodel does not support Py2Neo 3 and there is no word on what the plans for Neomodel are. I don't see any activity in fact.

**Comment by Ashwanthkumard** [comment]
@mjmare  : **Neo4j 3.0, py2neo 2.0.7**
Not updated py2neo, still able to query Neo4j 3.0 Sucessfully. Older version of Py2Neo is supporting the current version of Neo4j. But,
**Neomodel 2.0.2, Py2Neo 2.0.7, Unable to create nodes.**  
using the neomodel is failing. Whyyy?

**Comment by the4thv** [comment]
Hi @mjmare and @Ashwanthkumard , on the subject of work to support Neo4j 3.0, my colleague and I are taking on this work (as we use neomodel in production), with @nigelsmall moderating it. I will be starting the work this week.

Kind Regards,

Dave

**Comment by mjmare** [comment]
Really great news! Looking forward to it.

**Comment by Ashwanthkumard** [comment]
Waiting for the Release. Thanks for the Info.

**Comment by matgnt** [comment]
@the4thv thanks for taking this issue!
I wonder if you already have an update for us?
Can we help testing?

**Comment by the4thv** [comment]
hi @matgnt, thanks I will definitely take you up on that as soon as I'm ready (soon I hope!).

**Comment by robinedwards** [comment]
Hi guys, the current master now supports neo4j 3 using neo4j_driver backend.
