### ISSUE TITLE
ValueError when trying to filter on `id`

### ISSUE THREAD

**Issue by aaronst** [robinedwards/neomodel#241]
Trying to filter a NodeSet using the `id` property results in a `ValueError`.  For example...

```python
!#/usr/bin/env python3


from neomodel import config, db, clear_neo4j_database, StructuredNode
from neomodel import StringProperty


class Node(StructuredNode):
    """Generic Node"""

    name = StringProperty(required=True)


config.DATABASE_URL = 'bolt://neo4j:neo4j@localhost:7687'

n = Node(name='test')
n.save()

print(n.id)

m = Nodes.nodes.get(id=n.id)

clear_neo4j_database(db)
```

produces...

```python
45
Traceback (most recent call last):
  File "test_error.py", line 21, in <module>
    m = Node.nodes.get(id=n.id)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/neomodel/match.py", line 505, in get
    output = process_filter_args(self.source_class, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/neomodel/match.py", line 144, in process_filter_args
    raise ValueError("No such property {} on {}".format(prop, cls.__name__))
ValueError: No such property id on Node
```

**Comment by robinedwards** [comment]
Id isnt a property its an internal neo4j identifier and you should
generally avoid using it in your code.
