### ISSUE TITLE
AttributeError: module 'neomodel' has no attribute 'StructuredRel'

### ISSUE THREAD

**Issue by Kaleidophon** [robinedwards/neomodel#253]
Hi!

I am super confused because I was using neomodel for my project for weeks now and it was working flawlessly: 

    import neomodel

    class EveCompabilityMixin:
        """
        Extend neomodel classes to make them compatible with Eve API functions.
        """
        def __contains__(self, item):
            return item in vars(self)

        def __getitem__(self, item):
            return getattr(self, item)

        def __setitem__(self, key, value):
             setattr(self, key, value)

    class Relation(neomodel.StructuredRel, EveCompabilityMixin):
        """
        Node model for relations in the graph.
        """
        label = neomodel.StringProperty()
        data = neomodel.JSONProperty()

But suddenly today, after wanting to run my code, I received the following error:

    Traceback (most recent call last):
       File "/Users/admin/Desktop/bigworldgraph_/bigworldgraph/bwg/run.py", line 14, in <module>
    from bwg.neo4j import Neo4jLayer
       File "/Users/admin/Desktop/bigworldgraph_/bigworldgraph/bwg/neo4j.py", line 14, in <module>
    import neomodel
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neomodel/__init__.py", line 2, in <module>
    from .core import *
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neomodel/core.py", line 8, in <module>
    from .util import Database, classproperty, _UnsavedNode
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neomodel/util.py", line 11, in <module>
    from neo4j.v1 import GraphDatabase, basic_auth, CypherError
       File "/Users/admin/Desktop/bigworldgraph_/bigworldgraph/bwg/neo4j.py", line 31, in <module>
    class Relation(neomodel.StructuredRel, EveCompabilityMixin):
     AttributeError: module 'neomodel' has no attribute ‘StructuredRel'

Any ideas where this error originates? Thanks in advance!
P.S.: I am using neomodel version 3.2.3 with Python 3.5.3 on MacOS 10.10.5.

**Comment by Kaleidophon** [comment]
One of my modules was called neo4j.py, which produced this error. Sorry and never mind!
